### ISSUE TITLE
[Website]: Adding about us!

### ISSUE THREAD

**Issue by sristy17** [sristy17/Codess-Hackathon#25]
I request my teammates:

- [x] @sanskriti2005 
- [x] @jasmineanand 
- [x] @vansheeekaaa 

for the Codess hackathon to add their details and info about their contribution in this project, that's gonna show up in the website, about-us section!

**Comment by jasmineanand** [comment]
Added my description for ABOUT US Page [https://github.com/jasmineanand/Codess-Hackathon/commit/1345ba726501621e92ca5ee51592a1865bddcce6](url)

**Comment by jasmineanand** [comment]
I’ve added my details and contribution to the "About Us" section of the website. #30
