### ISSUE TITLE
Figma Prototype for the App

### ISSUE THREAD

**Issue by vansheeekaaa** [sristy17/Codess-Hackathon#7]
A discussion and planning for the Figma prototype of the app is required. The prototype will guide our design and development process, helping us visualize the user flow and interface for the various sections of the app. The goal is to ensure that the prototype is both intuitive and aligns with our objective.
 Sub-task 1: Outline the key features and sections that need to be included in the prototype.
 Sub-task 2: Defining wireframes for each section.
 Sub-task 3: Linking the sections together to create an user-flow.

 The prototype should be able to demonstrate the user flow and navigation between different sections.
 The design should reflect the core objectives of the app, ensuring that the prototype is user-friendly and accessible.

**Comment by sanskriti2005** [comment]
For the outline and the beginning (sub-task-1), I'd like to suggest a floating SOS or alert button that stays on the app throughout all sections.

Also section suggestions:
1) Home
2) Helpline
3) User section: The section we have with settings and where user can register themselves and add their emergency contacts and stuff
4) Chatbot section to provide support and send alerts whenever the user is in a location that is prone to crime.

**Comment by vansheeekaaa** [comment]
Here is the basic structure that I suggest, please add onto it.
1. Whenever any user opens the app, the name, logo, and tagline will be displayed first.
2. If we have a new user, we can implement a horizontal scroll feature that allows them to browse through a few key features of the app before prompting them to sign up.
3. For the sign-up process, we can have users enter their contact details, name, emergency contact, and then verify their accounts.
4. The front page can display a map that shows the user’s current location and categorizes areas based on safety levels. Also a search location on the top.
5. For areas marked with a risk above a certain threshold, an SOS will be sent automatically to the contact numbers provided during sign-up.
6. Below the map, we can include a floating button for the chatbot and a separate button for sending an SOS alert.
7. We can add a strip at the bottom of the screen that includes sections like "About Us" and "User Profile."

**Comment by sanskriti2005** [comment]
@vansheeekaaa Great work on this!!
